### ISSUE TITLE
不能运行

### ISSUE THREAD

**Issue by danfeng** [AppCanOpenSource/appcan-ios#66]
怎么使用，编译AppCanEngine后，再运行AppCanPlugin，直接报错。
Assertion failed: ([[NSFileManager defaultManager] fileExistsAtPath: [URL path]]), function +[BUtility addSkipBackupAttributeToItemAtURL:], file /Users/sun/Downloads/appcan-ios-master/webkitCorePalm/Classes/base/BUtility.m, line 1753.

![Uploading QQ20160316-0@2x.png…]()

**Comment by connyliu** [comment]
这个是空白的引擎工程，不包含任何网页文件的...
往widget目录下添加配置文件config.xml和网页文件就能运行了~
